SELECT * FROM TALUNO;


ALTER TABLE TALUNO ADD ESTADO CHAR(2) DEFAULT 'RS';

ALTER TABLE TALUNO ADD SALARIO NUMBER(8,2) DEFAULT 620;

UPDATE TALUNO SET
ESTADO = 'AC', SALARIO = 250
WHERE COD_ALUNO = 1;

UPDATE TALUNO SET
ESTADO = 'MT', SALARIO = 2000
WHERE COD_ALUNO = 3;

UPDATE TALUNO SET
ESTADO = 'BA', SALARIO = 800
WHERE COD_ALUNO = 5;

SELECT * FROM TALUNO;

COMMIT;


SELECT * FROM TALUNO
WHERE ESTADO <> 'RS'
AND SALARIO <= 800
ORDER BY SALARIO DESC;


INSERT INTO TALUNO (COD_ALUNO, NOME, CIDADE)
VALUES (SEQ_ALUNO.NEXTVAL, 'VALDIR' , 'DOIS IRMAOS');

INSERT INTO TALUNO(COD_ALUNO, NOME, CIDADE)
VALUES (SEQ_ALUNO.NEXTVAL, 'ALDO' , 'TRES IRMAOS');

UPDATE TALUNO SET
ESTADO = 'SP',
SALARIO = 900,
NOME = 'PEDRO'
WHERE COD_ALUNO = 25;

UPDATE TALUNO SET
ESTADO = 'SP'
WHERE COD_ALUNO = 5;



SELECT ESTADO, SALARIO, NOME FROM TALUNO
ORDER BY ESTADO, SALARIO DESC;

--INCLUIR NOVA COLUNA
ALTER TABLE TALUNO ADD NASCIMENTO DATE DEFAULT SYSDATE - 1000;



UPDATE TALUNO SET
NASCIMENTO = '10/09/2001'
WHERE COD_ALUNO = 1;


UPDATE TALUNO SET
NASCIMENTO = '10/08/2000'
WHERE COD_ALUNO = 2;

SELECT *FROM TALUNO;







