
SELECT NOME AS ALUNO FROM TCURSO;
SELECT COD_ALUNO, NOME, CIDADE FROM TALUNO;

SELECT COD_ALUNO AS "CODIGO", NOME AS "NOME DO ALUNO" FROM TALUNO;

SELECT * FROM TALUNO;

SELECT CIDADE FROM TALUNO;

SELECT DISTINCT CIDADE, NOME FROM TALUNO
ORDER BY NOME;
--ORDEM ALFABETICA


UPDATE TCONTRATO SET
DESCONTO = NULL
WHERE COD_CONTRATO = 4;

SELECT NOME AS CURSO,
    VALOR,
    VALOR / CARGA_HORARIA,
    Round(VALOR/CARGA_HORARIA,2) AS VALOR_HORA
FROM TCURSO
ORDER BY VALOR_HORA;

SELECT * FROM TCONTRATO;

SELECT COD_CONTRATO,
      DESCONTO,
      TOTAL,
      DESCONTO+TOTAL AS TESTANDO

FROM TCONTRATO;


SELECT COD_CONTRATO,
      DESCONTO,
      Nvl(DESCONTO,0) AS "TESTE DO NULL",
      TOTAL,
      Nvl(DESCONTO,0)+TOTAL AS TESTANDO

FROM TCONTRATO;





SELECT COD_ALUNO || ' - ' || NOME|| ' // ' || CIDADE AS ALUNO
FROM TALUNO
ORDER BY COD_ALUNO;


--ORDER BY CC;

